export { Hero } from "./hero"
export { About } from "./about"
export { Experience } from "./experience"
export { Projects } from "./projects"
export { Skills } from "./skills"
export { WhatIWorkOn } from "./what-i-work-on"
export { Github } from "./github"
export { Contact, Footer } from "./contact"
export { SectionLabel } from "./section-label"